In [1]:
import torch
def activation(x):
    return 1 / (1 + torch.exp(-x))

In [2]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [3]:
print(features.shape)
print(W1.shape)
print(W2.shape)

torch.Size([1, 3])
torch.Size([3, 2])
torch.Size([2, 1])


In [4]:
h = activation(torch.mm(features, W1) + B1)


In [5]:
output = activation(torch.mm(h, W2) + B2)

In [10]:
import numpy as np
a = np.random.rand(4,3)
print(a)
print(a.shape)

[[0.11383174 0.14946394 0.92063805]
 [0.96930799 0.29160009 0.78115793]
 [0.96314944 0.73399066 0.64860993]
 [0.51699694 0.87322525 0.47005116]]
(4, 3)


In [11]:
b = torch.from_numpy(a)
print(b)
print(b.shape)

tensor([[0.1138, 0.1495, 0.9206],
        [0.9693, 0.2916, 0.7812],
        [0.9631, 0.7340, 0.6486],
        [0.5170, 0.8732, 0.4701]], dtype=torch.float64)
torch.Size([4, 3])


In [14]:
c = b.numpy()
print(c)
print(c.shape)

[[0.11383174 0.14946394 0.92063805]
 [0.96930799 0.29160009 0.78115793]
 [0.96314944 0.73399066 0.64860993]
 [0.51699694 0.87322525 0.47005116]]
(4, 3)


In [15]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[0.2277, 0.2989, 1.8413],
        [1.9386, 0.5832, 1.5623],
        [1.9263, 1.4680, 1.2972],
        [1.0340, 1.7465, 0.9401]], dtype=torch.float64)

In [16]:
b

tensor([[0.2277, 0.2989, 1.8413],
        [1.9386, 0.5832, 1.5623],
        [1.9263, 1.4680, 1.2972],
        [1.0340, 1.7465, 0.9401]], dtype=torch.float64)

In [17]:
a

array([[0.22766348, 0.29892787, 1.8412761 ],
       [1.93861598, 0.58320018, 1.56231587],
       [1.92629888, 1.46798131, 1.29721985],
       [1.03399388, 1.7464505 , 0.94010231]])

In [ ]:
Numpy to Torch and back
Special bonus section! PyTorch has a great feature for converting between Numpy arrays and Torch tensors. To create a tensor from a Numpy array, use torch.from_numpy(). To convert a tensor to a Numpy array, use the .numpy() method.