In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.3.1


In [3]:
torch.cuda.is_available()

False

In [4]:
def activation(x):
    return 1 / (1 + torch.exp(-x))

In [5]:
torch.manual_seed(7)
features = torch.randn((1,5))
weights = torch.rand_like(features)
bias = torch.randn((1,1))

In [6]:
print(features.shape)
print(weights.shape)
print(bias.shape)

torch.Size([1, 5])
torch.Size([1, 5])
torch.Size([1, 1])


In [33]:
#The following cell show that 3 operations led to the same result. But * operator is not matrix multiplication

In [7]:
print(torch.sum(features * weights))
print(np.dot(features, np.transpose(weights)))
print(torch.mm(features, weights.view(5,1)))

tensor(1.3592)
[[1.3591546]]
tensor([[1.3592]])


In [8]:
output = activation(torch.sum(features * weights) + bias)

In [9]:
output2 = activation(torch.mm(features, weights.view(5,1)) + bias)
# tensor.view mostly used to change shapes because it 

In [10]:
print(output)
print(output == output2)

tensor([[0.6140]])
tensor([[True]])
